base_url = "https://tradeworks.co.za"
title = "tradeworks"

compile_sass = true

highlight_code = false

build_search_index = false

[extra]
greeting = "tradeworks"

iam = "I am"

links = [
    { title = "E-Mail", url = "mailto:info@tradeworks.co.za", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com", icon = "github" },
    { title = "Twitter", url = "https://twitter.com", icon = "twitter" }
]

[extra.author]
name = "Dave New"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"
