name = "hallo"
description = "A single-page theme to introduce yourself."
license = "MIT"
homepage = "https://github.com/janbaudisch/zola-hallo"
min_version = "0.4.0"
demo = "https://zola-hallo.janbaudisch.dev"

[extra]
greeting = "Hello!"

iam = "I am"

links = [
    { title = "E-Mail", url = "mailto:info@tradeworks.co.za", iconset = "fas", icon = "envelope" }
]

[extra.author]
name = "Dave New"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"

[author]
name = "Dave New"
